name: Testing CI/CD

on: 
  pull_request: 
    branches:
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Installing necessary deps
        run: npm install && npx prisma generate
      
      - name: Running tests
        run: npm run test